### ISSUE TITLE
Why aren't dependencies explicit?

### ISSUE THREAD

**Issue by jessetane** [pex-gl/pex#21]
Looking around I noticed that many packages in the pex-gl organization do not appear to explicitly reference each other via the dependencies field in their package.json files.

I noticed this:
https://github.com/pex-gl/pex/blob/master/lib/pkg/pex-packages-core.json

Which seems to make sure that if you use `pex init` your project gets all the right things installed, but I'm curious to understand why this approach is used over the more traditional dependencies field?

**Comment by vorg** [comment]
That's a very good question requiring a bit longer answer but I'll start here to keep the conversation going.

###  I wanted to avoid module duplication.

If every package require let's say `pex-context` then we might end up with the following folder structure
```
node_modules
   pex-sys
       node_modules
           pex-context@1.0.1
   pex-typo
       node_modules
           pex-context@1.0.2
```

While ideally this would be deduped as both versions are compatible in the previous versions of pex 0.3.x that wasn't the case (every minor version < 1.0.0 is treated like major by npm and potentially breaking)

That causes two problems

a) Couple of methods did and still do type checks. e.g. 

`pex-context@1.0.1/Texture2D` != `pex-context@1.0.2/Texture2D`

I'm trying to avoid this in the newer code e.g. when comparing two params

`if (param1.getTarget && param2.getTarget && (param1.getTarget() == param2.getTarget()))`

b) In PEX <1.0 Context was global and you would call `var gl = Context.getCurrent()`. With module like above the singletons are not possible (you would end up with 2 Contexts)

This has changed in PEX@1.0.+ as now we pass `ctx` object to all dependencies

###  Peer references

We did use peer references in [the past](https://github.com/pex-gl/pex-typo/blob/c139f94453fb31a42d135d1f5780e1fcfc5abcfd/package.json#L22 )

```
"peerDependencies": {
    "pex-glu": "0.x",
    "pex-color": "0.x",
    "pex-gen": "0.x",
    "pex-geom": "0.x"
  },
```

But when npm@3 stopped installing them I didn't continue using them.

### Solutions

I'm open for suggestions and best practices in this kind of plugin scenarios that pex and pex-* modules are at the moment.

**Comment by jessetane** [comment]
That makes sense, thank you for the thorough explanation. Maybe you've looked at this:
https://github.com/mrdoob/three.js/issues/4776

where some of the same problems are discussed. in particular the type checking issue comes up, with a feature detection approach being suggested over instanceof / constructor equality tests.

Generally it sounds like pex has fewer, more well defined problems than threejs though - maybe it's just a matter of spec'ing out all the deps, doing `npm i` and watching to see what breaks? I started to try that myself but got hung up on dealing with the require calls to plask. I see you can use browserify's ignore flag to work around the problem but that doesn't feel quite right. A "plask-wrap" module or similar with a browser field in its pkg json might do the trick, and the rest seems like it could fall into place naturally enough. Obviously still a bunch of work, I know :)

**Comment by jessetane** [comment]
Also, personal taste I suppose, but I would risk code duplication to get familiar dependency management. Getting all the version mismatches fixed upstream to resolve duplication problems can be a pain, but at least no actual code needs to get changed - just version numbers in other package.json files.

**Comment by vorg** [comment]
I like the idea about `plask-wrap`. I'll try to prototype it today and see what's possible.

> I would risk code duplication to get familiar dependency management. 

Can you explain how would that work? Do you expect the user to dedupe code after npm install?

**Comment by vorg** [comment]
Ideally I would love to get rid of peer dependencies completely but i don't know if it's possible given the current architecture and WebGL state machine in general

This happened so many times for me and also the reason why modules like [pex-typo](https://github.com/pex-gl/pex-typo) are still not ported..

<img width="917" alt="screen shot 2016-06-21 at 18 24 26" src="https://cloud.githubusercontent.com/assets/171001/16516656/0583df36-3f71-11e6-9729-17c03adc13ad.png">
(Screen from https://www.youtube.com/watch?v=a97Mw2z1SAI)

**Comment by vorg** [comment]
Ok, first step is behind us

[plask-wrap@1.0.0](https://www.npmjs.com/package/plask-wrap)

These modules no longer need `-i plask` flag
`pex-sys v1.5.1` updated in https://github.com/pex-gl/pex-sys/commit/e9b2407554a4f994d4ad27f5fae676e3e4250cff
`pex-context v1.3.0` updated in https://github.com/pex-gl/pex-context/commit/f4b2eeae8f56fd60ba95112d8e63227c26a3912a
`pex-io v1.2.0` updated in https://github.com/pex-gl/pex-io/commit/6b36dbc4c8764f6a8c4e4519c9c58769acba94fc

Still need to update `pex-gui`

**Comment by jessetane** [comment]
Awesome!

> Ideally I would love to get rid of peer dependencies completely but i don't know if it's possible given the current architecture and WebGL state machine in general

I am not really familiar enough with the relevant packages, or even WebGL tbh, but it sounded like you were saying instances of pex-context represented the memory that needed to get shared, and that internally most of the required changes to allow consumers to pass their own reference had already been made.

Maybe that task is not as easy as I am assuming - I do see usage of an API `this.getContext()` in the example, which I am naively thinking might be changeable to something more like:

```javascript
var Context      = require('pex-context');
var Window          = require('pex-sys/Window');

Window.create({
    context: new Context(),
    settings: {
        ...
```

**Comment by jessetane** [comment]
Regarding code duplication, ideally npm3 improves the situation enough, but I think unless you pin exact versions or are able to be really meticulous about updating dependents in step, this is always a risk... I am just saying that as long as there is no technical requirement for there to be a single constructor for any given type, I think this is probably acceptable. People who care about bundle size will hopefully notice and if a reinstall or dedupe doesn't fix their problem, send patches to fix legitimately out of date dependencies.

**Comment by vorg** [comment]
```
Window.create({
    context: new Context(),
```

This is currently not possible as Context creation is platform specific and that functionality is within Window. Peer dependencies problem in pex has two versions.

## Explicit

In `pex-sys/WindowImplBrowser`:
```
var Context  = require('pex-context/Context');
...
windowPex._ctx = new Context(gl);
```

We should probably add `pex-context` to the package json of `pex-sys` as we require it.

## Implicit

In `pex-gui/GUI`:

```
function GUI(ctx, windowWidth, windowHeight, pixelRatio) {
...
ctx.createMesh()
```

Where we don't do node require for `pex-context` but we assume that what we get as `ctx` is certain version of the `pex-context/Context` that has `createMesh` method. I don't know how to get rid of that kind of dependency.
