### ISSUE TITLE
Cannot find module 'pex-context'/Context

### ISSUE THREAD

**Issue by oliverellmers** [pex-gl/pex#27]
Hello,

I have been trying to get started with Pex and it appears that the example project created is incorrect. Which is the correct module to be linking to and how to do so correctly in a Pex project?

Initial error I recieve when running the pex turotial is:

`Cannot find module 'pex-cam/PerspCamera' from 'path/to/exampleApp'`

I fix this error (and an error searching for Arcball as well ) by changing in main.js

the variables to:
`var PerspCamera = require('pex-cam/perspective');
var Arcball = require('pex-cam/orbiter');`

But now have a new error

`Error: Cannot find module 'pex-Context/Context'`

There is no variable in example main.js - so how do we link to this and what is the correct module in the pex-context file?

On a side note - I notie this repo is quite old... is there any continued development on Pex? And if not, what is it that Variable are using as an alternative?

Best,

O.

**Comment by vorg** [comment]
Hi, I've updated readme as this command line utility is not maintained at the moment. Please have a look https://github.com/pex-gl/pex/blob/master/README.md
